### ISSUE TITLE
dock when breakpoint is hit

### ISSUE THREAD

**Issue by thushara5884** [azouaoui-med/react-pro-sidebar#41]
how to make the side bar collpased when the breakpoint is hit?

**Comment by DannyBroadhurst** [comment]
Did anyone ever get a solution to this?
ATM when the breakpoint is hit the sidebar just disappears.

**Comment by AliFahmy** [comment]
@DannyBroadhurst Did you find a solution for this issue?

**Comment by kylemcguinn** [comment]
My guess is that the intention of the responsive breakpoint is to hide the menu completely so that you can then display a more mobile friendly menu. You could listen for window resize events and update the menu's "collapsed" state if you wanted to imitate the responsive behavior.


`const responseBreakpoint = 576;
    const [width, setWidth] = useState(0);

    useLayoutEffect(() => {
        function updateSize() {
            setWidth(window.innerWidth);
        }
        window.addEventListener('resize', updateSize);
        updateSize();
        return () => window.removeEventListener('resize', updateSize);
    }, []);` 
    
    `<ProSidebar collapsed={width < responseBreakpoint}>`

**Comment by azouaoui-med** [comment]
as from v1.x you can now make use of `useProSidebar` hook to access and manage sidebar state 

```
  const { collapseSidebar, broken } = useProSidebar();

  React.useEffect(() => {
    if (broken) collapseSidebar();
  }, [broken, collapseSidebar]);
```
